name: GitHub Actions Demo
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Trigerem jest ->${{ github.event_name }}<- event."
      - run: echo "Twoj branch ->${{ github.ref }}<- , repozytorium ->${{ github.repository }}<-."
      - run: echo "Job dziala na systemie ->${{ runner.os }}<- by GitHub!"


  test_after_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repozytorium
        uses: actions/checkout@v3
      - run: echo "Repozytorium ->${{ github.repository }}<- repo zostalo sklonowane przez runnera"
      - run: echo "Workflow gotowe. Czas zaczac faze testow"
      - name: Wypisz liste plikow
        run: |
          ls ${{ github.workspace }}
          echo "----------"
          echo "Pliki w obrazie."
      - name: "Status joba."
        run: echo "Status joba jest ->${{ job.status }}<-."

      - name: Zainstaluj niezbedne skladniki (mathplotlib+numpy)
        run: make deps

      - name: Uruchom simple_file.py
        run: make run
