name: GitHub Actions Demo
run-name: Deploy by ->${{ github.actor }}<-

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Trigerem jest ->${{ github.event_name }}<- event."
      - run: echo "Twoj branch ->${{ github.ref }}<- , repozytorium ->${{ github.repository }}<-."
      - run: echo "Job dziala na systemie ->${{ runner.os }}<- by GitHub!"


  test_after_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repozytorium
        uses: actions/checkout@v3
      - run: echo "Repozytorium ->${{ github.repository }}<- repo zostalo sklonowane przez runnera"
      - run: echo "Workflow gotowe. Czas zaczac faze testow"
      - name: File list
        run: |
          ls ${{ github.workspace }}
          echo "----------"
      - name: Job status
        run: echo "Job status ->${{ job.status }}<-."

      - name: Install requirements - (mathplotlib+numpy) and selenium
        run: make deps

      - name: Run - simple_file.py and tests
        run: make run

  send_to_docker:
    runs-on: ubuntu-latest
    needs: test_after_build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: adamosses/simple_file:1.1